# Generated by Django 5.0 on 2024-04-13 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptvariable',
            name='prompt',
            field=models.CharField(default='1girl', max_length=100),
        ),
        migrations.AlterField(
            model_name='promptvariable',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot.user'),
        ),
    ]
