# Generated by Django 5.0 on 2024-04-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_promptvariable_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptvariable',
            name='hr_checkpoint_name',
            field=models.CharField(default='calicomix', max_length=100),
        ),
    ]
